paths:
  /FITple/login:
    post:
      tags:
        - Login
      summary: 로그인
      parameters:
      - name: login
        in: body
        required: true
        schema:
          properties:
            user_id:
              type: string
              description: 유저 아이디
              example: swaggerTest
            password:
              type: string
              description: 유저 비밀번호
              example: 1234567
      responses:
        '200':
          description: 로그인 성공!
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: true
              code:
                type: string
                example: 2000
              message:
                type: string
                example: "success!"
        '400':
          description: 잘못된 요청
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: false
              code:
                type: string
                example: 400
              message:
                type: string
                example: 잘못된 요청입니다
        '401':
          description: 존재하지 않는 아이디
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: false
              code:
                type: string
                example: 401
              message:
                type: string
                example: 존재하지 않는 아이디입니다.
        '402':
          description: 비어있는 데이터
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: false
              code:
                type: string
                example: 402
              message:
                type: string
                example: 데이터가 비어있습니다.
        '403':
          description: 일치하지 않는 비밀번호
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: false
              code:
                type: string
                example: 403
              message:
                type: string
                example: 비밀번호가 일치하지 않습니다.
        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              isSuccess:
                type: boolean
                example: false
              code:
                type: string
                example: 500
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.